const X2 = (fr, en) => ({ fr, en });
const ex2 = (title, context, code, explanation) => ({ title: X2(...title), context: X2(...context), code, explanation: X2(...explanation) });
const task2 = (title, prompt, solution, correction) => ({ title: X2(...title), prompt: X2(...prompt), solution, correction: X2(...correction) });
const E = {
  basics: {
    examples: [
      ex2(['01 · Vitesse moyenne','01 · Average speed'],['Un cycliste parcourt 42 km en 2 h.','A cyclist covers 42 km in 2 h.'],'distance = 42\nduree = 2\nprint(distance / duree)',['La vitesse moyenne est une distance divisée par une durée.','Average speed is distance divided by time.']),
      ex2(['02 · Kelvin','02 · Kelvin'],['Un laboratoire convertit 25 °C en kelvins.','A lab converts 25°C to kelvins.'],'celsius = 25\nkelvin = celsius + 273.15\nprint(kelvin)',['La conversion ajoute 273.15 sans modifier la valeur initiale.','The conversion adds 273.15 without modifying the initial value.']),
      ex2(['03 · Énergie','03 · Energy'],['On estime une énergie potentielle avec une masse, g et une hauteur.','Potential energy is estimated from mass, g, and height.'],'masse = 2\ng = 9.81\nhauteur = 3\nprint(masse * g * hauteur)',['Chaque variable porte une unité et la formule est traduite directement.','Each variable carries a unit and the formula is translated directly.']),
      ex2(['04 · Fréquence cardiaque','04 · Heart rate'],['Une séance calcule une fréquence maximale théorique.','A session calculates a theoretical maximum heart rate.'],'age = 16\nfcm = 220 - age\nprint(fcm)',['La formule met en relation une donnée saisie et une constante.','The formula links an input value to a constant.']),
      ex2(['05 · Loi d’Ohm','05 · Ohm law'],['Un circuit connaît la tension et la résistance.','A circuit knows voltage and resistance.'],'tension = 12\nresistance = 6\nintensite = tension / resistance\nprint(intensite)',['La variable intensite reçoit le résultat du quotient U/R.','intensite receives the quotient U/R.'])
    ],
    exercises: [
      task2(['11 · Débit','11 · Flow rate'],['Calcule le débit de 10 L écoulés en 5 min.','Calculate the flow rate of 10 L in 5 min.'],'volume = 10\nduree = 5\nprint(volume / duree)',['Le débit est un volume divisé par le temps.','Flow rate is volume divided by time.']),
      task2(['12 · Masse volumique','12 · Density'],['Calcule la masse volumique de 250 g pour 100 cm³.','Calculate density for 250 g in 100 cm³.'],'masse = 250\nvolume = 100\nprint(masse / volume)',['La formule rho = m/V devient une division.','The formula rho = m/V becomes a division.']),
      task2(['13 · Calorie MET','13 · MET calories'],['Estime 8 kcal par minute pendant 30 minutes.','Estimate 8 kcal per minute for 30 minutes.'],'kcal_minute = 8\nduree = 30\nprint(kcal_minute * duree)',['Le total est un produit durée × dépense.','The total is duration × expenditure.']),
      task2(['14 · ADN vers ARN','14 · DNA to RNA'],['Remplace la thymine T par U dans une séquence.','Replace thymine T with U in a sequence.'],'adn = "ATGCTT"\nprint(adn.replace("T", "U"))',['replace transforme une chaîne sans boucle explicite.','replace transforms a string without an explicit loop.']),
      task2(['15 · Pendule','15 · Pendulum'],['Calcule la période avec T = 2*pi*sqrt(L/g).','Calculate period with T = 2*pi*sqrt(L/g).'],'from math import pi, sqrt\nlongueur = 1\ng = 9.81\nprint(2 * pi * sqrt(longueur / g))',['La bibliothèque math fournit pi et sqrt.','The math library provides pi and sqrt.'])
    ]
  },
  logic: {
    examples: [
      ex2(['06 · États de l’eau','06 · Water states'],['Classe l’eau selon sa température.','Classify water by temperature.'],'t = -4\nif t < 0: print("solide")\nelif t < 100: print("liquide")\nelse: print("gaz")',['Les seuils 0 et 100 forment trois intervalles.','Thresholds 0 and 100 form three intervals.']),
      ex2(['07 · IMC','07 · BMI'],['Un diagnostic pédagogique classe un IMC.','A learning diagnostic classifies BMI.'],'imc = 27.4\nif imc < 18.5: c = "insuffisant"\nelif imc < 25: c = "normal"\nelif imc < 30: c = "surpoids"\nelse: c = "obésité"\nprint(c)',['Les conditions sont ordonnées du seuil le plus bas au plus haut.','Conditions are ordered from the lowest to the highest threshold.']),
      ex2(['08 · Triangle','08 · Triangle'],['On identifie un triangle grâce à ses trois côtés.','A triangle is identified from its three sides.'],'a, b, c = 3, 3, 5\nif a == b == c: print("équilatéral")\nelif a == b or a == c or b == c: print("isocèle")\nelse: print("scalène")',['Les comparaisons décrivent l’égalité des côtés.','Comparisons describe side equality.']),
      ex2(['09 · pH','09 · pH'],['Une solution est acide, neutre ou basique.','A solution is acidic, neutral, or basic.'],'ph = 8.2\nif ph < 7: print("acide")\nelif ph == 7: print("neutre")\nelse: print("basique")',['Les trois branches couvrent les trois zones du pH.','The three branches cover the three pH zones.']),
      ex2(['10 · Indice UV','10 · UV index'],['Une application conseille une protection selon l’indice UV.','An app recommends protection from the UV index.'],'uv = 7\nif uv <= 2: conseil = "faible"\nelif uv <= 5: conseil = "modérée"\nelse: conseil = "forte"\nprint(conseil)',['Un seuil inclusif se traduit par <=.','An inclusive threshold is written with <=.'])
    ],
    exercises: [
      task2(['11 · Archimède','11 · Archimedes'],['Dis si un objet flotte quand sa densité est inférieure à celle de l’eau.','Say whether an object floats when its density is lower than water.'],'densite = 0.8\nprint("flotte" if densite < 1 else "coule")',['La comparaison choisit l’issue physique.','The comparison chooses the physical outcome.']),
      task2(['12 · Année bissextile','12 · Leap year'],['Teste la règle des années bissextiles.','Test the leap-year rule.'],'annee = 2024\nprint(annee % 400 == 0 or (annee % 4 == 0 and annee % 100 != 0))',['Les opérateurs and/or transcrivent la règle logique.','and/or operators transcribe the logical rule.']),
      task2(['13 · Lentille','13 · Lens'],['Classe une lentille par sa vergence.','Class a lens from its power.'],'vergence = -2\nprint("convergente" if vergence > 0 else "divergente")',['Le signe de la vergence suffit pour cette classification.','The sign of power is enough for this classification.']),
      task2(['14 · Tension artérielle','14 · Blood pressure'],['Signale une tension systolique à surveiller si elle dépasse 140.','Flag systolic pressure above 140.'],'systolique = 145\nif systolique > 140: print("à surveiller")\nelse: print("dans la zone")',['Le seuil déclenche une information, pas un diagnostic médical.','The threshold triggers information, not a medical diagnosis.']),
      task2(['15 · Pythagore','15 · Pythagorean theorem'],['Vérifie si trois longueurs peuvent former un triangle rectangle.','Check if three lengths form a right triangle.'],'a, b, c = 3, 4, 5\nprint(a*a + b*b == c*c)',['Le carré de l’hypoténuse est comparé à la somme des carrés.','The square of the hypotenuse is compared with the sum of squares.'])
    ]
  },
  functions: {
    examples: [
      ex2(['06 · Aire d’un disque','06 · Circle area'],['Une fonction calcule l’aire pour plusieurs rayons.','A function calculates area for several radii.'],'from math import pi\ndef aire_disque(r):\n    return pi * r ** 2\nprint(aire_disque(3))',['Le rayon est local au calcul et return rend la valeur réutilisable.','The radius is local to the calculation and return makes the value reusable.']),
      ex2(['07 · Vitesse','07 · Speed'],['Une fonction calcule une vitesse moyenne avec unités explicites.','A function calculates average speed with explicit units.'],'def vitesse(distance_km, temps_h):\n    return distance_km / temps_h\nprint(vitesse(42, 2))',['Deux arguments entrent, une valeur numérique sort.','Two arguments enter, one numeric value leaves.']),
      ex2(['08 · Énergie','08 · Energy'],['Un modèle calcule une énergie de pesanteur.','A model calculates gravitational energy.'],'def energie(masse, g, hauteur):\n    return masse * g * hauteur\nprint(energie(2, 9.81, 3))',['La fonction isole la formule scientifique.','The function isolates the scientific formula.']),
      ex2(['09 · Concentration','09 · Concentration'],['Une solution est décrite par une masse dissoute et un volume.','A solution is described by dissolved mass and volume.'],'def concentration(masse, volume):\n    return masse / volume\nprint(concentration(12, 0.5))',['Le contrat suppose un volume non nul.','The contract assumes a non-zero volume.']),
      ex2(['10 · Pression','10 · Pressure'],['Une fonction transforme une valeur en catégorie informative.','A function turns a value into an informative category.'],'def zone_pression(valeur):\n    if valeur < 90: return "basse"\n    if valeur <= 120: return "habituelle"\n    return "élevée"\nprint(zone_pression(128))',['Une fonction peut combiner conditions et return.','A function can combine conditions and return.'])
    ],
    exercises: [
      task2(['11 · FCM','11 · Max heart rate'],['Crée fcm(age) avec 220 - âge.','Create fcm(age) with 220 - age.'],'def fcm(age):\n    return 220 - age',['Le paramètre age est utilisé uniquement dans la fonction.','age is used only inside the function.']),
      task2(['12 · Kelvin','12 · Kelvin'],['Crée celsius_vers_kelvin(c).','Create celsius_to_kelvin(c).'],'def celsius_vers_kelvin(c):\n    return c + 273.15',['La fonction renvoie une nouvelle unité.','The function returns a new unit.']),
      task2(['13 · Loi d’Ohm','13 · Ohm law'],['Crée intensite(u, r).','Create current(u, r).'],'def intensite(u, r):\n    return u / r',['Le calcul U/R est isolé et testable.','The U/R calculation is isolated and testable.']),
      task2(['14 · Parité','14 · Parity'],['Crée est_pair(n) avec un booléen.','Create is_even(n) with a boolean.'],'def est_pair(n):\n    return n % 2 == 0',['Le résultat est directement réutilisable dans if.','The result is directly reusable in if.']),
      task2(['15 · Deux appels','15 · Two calls'],['Teste vitesse sur deux trajets.','Test speed on two routes.'],'def vitesse(d, t): return d / t\nassert vitesse(100, 2) == 50\nassert vitesse(30, 1.5) == 20',['assert transforme les attentes en tests lisibles.','assert turns expectations into readable tests.'])
    ]
  },
  vectors: {
    examples: [
      ex2(['06 · Vitesse par jour','06 · Daily speed'],['Un tableau contient les distances de quatre jours.','A vector stores four daily distances.'],'distances = [12, 18, 15, 21]\nfor d in distances: print(d / 2)',['Le parcours applique la même règle à chaque mesure.','Traversal applies the same rule to every measurement.']),
      ex2(['07 · Températures filtrées','07 · Filtered temperatures'],['Une station conserve les températures supérieures à 20 °C.','A station keeps temperatures above 20°C.'],'mesures = [18, 22, 25, 19]\nchaudes = [t for t in mesures if t > 20]\nprint(chaudes)',['Le filtrage construit une liste plus ciblée.','Filtering builds a more focused list.']),
      ex2(['08 · Energie totale','08 · Total energy'],['Un vecteur contient des énergies mesurées pendant une expérience.','A vector contains energies measured during an experiment.'],'energies = [3.2, 4.1, 2.7]\nprint(sum(energies))',['sum donne le total sans perdre les valeurs originales.','sum gives the total without losing original values.']),
      ex2(['09 · Position du pic','09 · Peak position'],['On cherche le jour correspondant à la température maximale.','Find the day corresponding to the maximum temperature.'],'temperatures = [19, 24, 22, 27]\nprint(temperatures.index(max(temperatures)))',['index transforme la valeur maximale en position.','index turns the maximum value into a position.']),
      ex2(['10 · Normalisation','10 · Normalization'],['Des mesures sont ramenées entre 0 et 1.','Measurements are scaled between 0 and 1.'],'mesures = [10, 20, 30]\nmini, maxi = min(mesures), max(mesures)\nprint([(x-mini)/(maxi-mini) for x in mesures])',['La formule utilise les deux extrêmes du vecteur.','The formula uses both vector extremes.'])
    ],
    exercises: [
      task2(['11 · Vitesse moyenne','11 · Average speed'],['Calcule la moyenne de quatre vitesses.','Calculate the mean of four speeds.'],'vitesses = [8, 10, 12, 10]\nprint(sum(vitesses) / len(vitesses))',['L’effectif est pris dans la liste elle-même.','The count comes from the list itself.']),
      task2(['12 · Valeurs négatives','12 · Negative values'],['Compte les températures sous zéro.','Count temperatures below zero.'],'temperatures = [-2, 4, -1, 3]\nprint(sum(t < 0 for t in temperatures))',['Les booléens peuvent être additionnés comme 0 et 1.','Booleans can be added as 0 and 1.']),
      task2(['13 · Accumulation','13 · Accumulation'],['Calcule une distance cumulée.','Calculate cumulative distance.'],'distances = [2, 3, 4]\ncumul = 0\nfor d in distances:\n    cumul += d\nprint(cumul)',['L’accumulateur conserve l’état entre les tours.','The accumulator keeps state between turns.']),
      task2(['14 · Index du maximum','14 · Maximum index'],['Trouve la position du plus grand courant.','Find the position of the largest current.'],'courants = [2.1, 3.4, 2.8]\nprint(courants.index(max(courants)))',['max puis index relient valeur et position.','max then index link value and position.']),
      task2(['15 · Unités','15 · Units'],['Convertis toutes les longueurs de cm en m.','Convert all lengths from cm to m.'],'longueurs = [30, 45, 120]\nprint([x / 100 for x in longueurs])',['La compréhension applique la conversion à chaque élément.','The comprehension applies the conversion to every item.'])
    ]
  },
  dictionaries: {
    examples: [
      ex2(['06 · Mesure scientifique','06 · Scientific measurement'],['Un dictionnaire associe une valeur à son unité et à son capteur.','A dictionary links a value to its unit and sensor.'],'mesure = {"valeur": 21.4, "unite": "°C", "capteur": "S1"}\nprint(mesure["valeur"], mesure["unite"])',['Les clés rendent le contexte de la valeur explicite.','Keys make the value’s context explicit.']),
      ex2(['07 · Fréquence par sport','07 · Frequency by sport'],['Un profil sportif conserve une fréquence cardiaque par activité.','A sports profile stores heart rate by activity.'],'fc = {"repos": 65, "course": 154}\nprint(fc.get("natation", "non mesurée"))',['get gère une activité encore absente.','get handles an activity not yet recorded.']),
      ex2(['08 · Composition chimique','08 · Chemical composition'],['Les proportions d’un mélange sont stockées par élément.','Mixture proportions are stored by element.'],'proportions = {"eau": 70, "sel": 5, "solvant": 25}\nprint(sum(proportions.values()))',['values permet de contrôler le total des proportions.','values makes it possible to check total proportions.']),
      ex2(['09 · Compter des catégories','09 · Count categories'],['Un dictionnaire compte les observations par catégorie.','A dictionary counts observations by category.'],'compte = {}\nfor etat in ["solide", "liquide", "liquide"]:\n    compte[etat] = compte.get(etat, 0) + 1\nprint(compte)',['get fournit zéro au premier passage d’une catégorie.','get provides zero on the first occurrence of a category.']),
      ex2(['10 · Configuration','10 · Configuration'],['Un protocole garde ses paramètres expérimentaux nommés.','A protocol keeps named experimental parameters.'],'protocole = {"duree": 60, "temperature": 25, "agitation": True}\nfor cle, valeur in protocole.items(): print(cle, valeur)',['items parcourt la configuration sans perdre le nom du paramètre.','items traverses configuration without losing parameter names.'])
    ],
    exercises: [
      task2(['11 · Score par élève','11 · Score per student'],['Crée un dictionnaire des scores et affiche le score de Lina.','Create a score dictionary and display Lina’s score.'],'scores = {"Lina": 16, "Ali": 12}\nprint(scores["Lina"])',['La clé est le nom de l’élève.','The key is the learner name.']),
      task2(['12 · Stock sécurisé','12 · Safe inventory'],['Mets à jour un stock seulement si la clé existe.','Update stock only when the key exists.'],'stock = {"cahier": 12}\nif "cahier" in stock: stock["cahier"] -= 1',['in protège l’accès avant la mise à jour.','in protects access before updating.']),
      task2(['13 · Moyenne matières','13 · Subject mean'],['Calcule la moyenne des valeurs d’un dictionnaire de notes.','Calculate the mean of grade values.'],'notes = {"maths": 14, "python": 18}\nprint(sum(notes.values()) / len(notes))',['values extrait les données numériques.','values extracts numeric data.']),
      task2(['14 · Inverser clé-valeur','14 · Invert key-value'],['Crée un dictionnaire code vers nom à partir de nom vers code.','Create code-to-name from name-to-code.'],'noms = {"Na": "sodium", "O": "oxygene"}\ninverse = {nom: code for code, nom in noms.items()}',['La compréhension inverse les deux rôles.','The comprehension swaps the two roles.']),
      task2(['15 · Présence d’un champ','15 · Field presence'],['Affiche une valeur de secours si la pression manque.','Display a fallback if pressure is missing.'],'mesure = {"temperature": 20}\nprint(mesure.get("pression", "absente"))',['get évite KeyError et rend le programme robuste.','get avoids KeyError and makes the program robust.'])
    ]
  },
  records: {
    examples: [
      ex2(['06 · Athlète','06 · Athlete'],['Une fiche regroupe nom, distance et temps d’un coureur.','A record groups a runner’s name, distance, and time.'],'athlete = {"nom": "Nora", "distance": 5, "temps": 28}\nprint(athlete["distance"] / (athlete["temps"] / 60))',['Les champs permettent de calculer l’allure à partir d’une fiche.','Fields allow pace calculation from a record.']),
      ex2(['07 · Expérience','07 · Experiment'],['Une expérience stocke une température, une masse et un résultat.','An experiment stores temperature, mass, and result.'],'experience = {"temperature": 25, "masse": 12.4, "resultat": "stable"}\nif experience["resultat"] == "stable": print("valider")',['Le champ resultat pilote la décision de validation.','The result field drives the validation decision.']),
      ex2(['08 · Validation d’un dossier','08 · File validation'],['Un dossier est accepté si ses champs obligatoires sont présents.','A file is accepted if required fields are present.'],'dossier = {"nom": "Samir", "email": "samir@example.com"}\nobligatoires = ["nom", "email"]\nprint(all(cle in dossier for cle in obligatoires))',['all vérifie toutes les clés attendues.','all checks every expected key.']),
      ex2(['09 · Liste de mesures','09 · Measurement records'],['Plusieurs fiches représentent les mesures de capteurs.','Several records represent sensor readings.'],'mesures = [{"id": 1, "valeur": 18}, {"id": 2, "valeur": 22}]\nprint([m["valeur"] for m in mesures])',['Une liste de dictionnaires forme une table simple.','A list of dictionaries forms a simple table.']),
      ex2(['10 · Rapport','10 · Report'],['Une fiche complète produit un compte rendu lisible.','A complete record produces a readable report.'],'eleve = {"prenom": "Lina", "notes": [14, 16]}\nmoy = sum(eleve["notes"]) / len(eleve["notes"])\nprint(f"{eleve[\"prenom\"]}: {moy}")',['Le calcul utilise notes puis le nom sert à présenter le résultat.','The calculation uses notes then the name presents the result.'])
    ],
    exercises: [
      task2(['11 · Fiche pression','11 · Pressure record'],['Crée un enregistrement avec systolique, diastolique et date.','Create a record with systolic, diastolic, and date.'],'mesure = {"systolique": 120, "diastolique": 80, "date": "2026-06-01"}',['Les trois champs décrivent une même mesure.','The three fields describe one measurement.']),
      task2(['12 · Filtrer fiches','12 · Filter records'],['Garde les mesures dont valeur dépasse 20.','Keep measurements whose value exceeds 20.'],'mesures = [{"valeur": 18}, {"valeur": 24}]\nprint([m for m in mesures if m["valeur"] > 20])',['Le filtre porte sur un champ du record.','The filter targets a record field.']),
      task2(['13 · Complétude','13 · Completeness'],['Teste si chaque élève possède un identifiant.','Test whether each student has an identifier.'],'eleves = [{"id": 1}, {"id": 2}]\nprint(all("id" in e for e in eleves))',['La validation parcourt toute la liste de fiches.','Validation traverses the whole record list.']),
      task2(['14 · Mise à jour','14 · Update'],['Augmente le stock d’un produit après livraison.','Increase a product stock after delivery.'],'produit = {"nom": "Tube", "stock": 4}\nproduit["stock"] += 6',['On modifie le champ ciblé sans perdre les autres.','Only the target field is modified.']),
      task2(['15 · Recherche identifiant','15 · Search identifier'],['Trouve la fiche dont id vaut 2.','Find the record whose id is 2.'],'eleves = [{"id": 1, "nom": "Ali"}, {"id": 2, "nom": "Nora"}]\nprint(next(e for e in eleves if e["id"] == 2))',['next récupère la première fiche qui respecte le test.','next retrieves the first record matching the test.'])
    ]
  },
  stacks: {
    examples: [
      ex2(['06 · Parenthèses','06 · Parentheses'],['Une pile aide à vérifier des parenthèses ouvrantes et fermantes.','A stack helps check opening and closing parentheses.'],'pile = []\nfor symbole in "(()":\n    if symbole == "(": pile.append(symbole)\nprint(len(pile))',['Chaque ouverture est empilée et attend une fermeture.','Each opening is pushed and awaits a closing symbol.']),
      ex2(['07 · ADN inverse','07 · Reverse DNA'],['Une séquence est relue dans l’ordre inverse avec une pile.','A sequence is read in reverse using a stack.'],'pile = list("ATGC")\nretour = ""\nwhile pile: retour += pile.pop()\nprint(retour)',['Le dernier caractère entré devient le premier lu.','The last character entered becomes the first read.']),
      ex2(['08 · Historique scientifique','08 · Scientific history'],['Un logiciel annule la dernière transformation appliquée à une mesure.','Software undoes the last transformation applied to a measurement.'],'historique = ["filtre", "normalisation", "arrondi"]\nprint("annuler", historique.pop())',['pop retire l’opération la plus récente.','pop removes the most recent operation.']),
      ex2(['09 · Appels imbriqués','09 · Nested calls'],['Une pile conceptuelle représente des fonctions qui s’appellent.','A conceptual stack represents calling functions.'],'appels = ["main", "analyser", "moyenne"]\nprint(appels[-1])\nappels.pop()',['Le sommet représente l’appel actif le plus récent.','The top represents the most recent active call.']),
      ex2(['10 · Expression postfixée','10 · Postfix expression'],['Une pile stocke des opérandes avant une opération.','A stack stores operands before an operation.'],'pile = [3, 4]\nb = pile.pop(); a = pile.pop()\nprint(a + b)',['Les deux derniers éléments sont récupérés dans l’ordre du calcul.','The two latest items are retrieved for the calculation.'])
    ],
    exercises: [
      task2(['11 · Annulation sûre','11 · Safe undo'],['Écris une fonction annuler(pile) qui renvoie None si vide.','Write annuler(stack) returning None if empty.'],'def annuler(pile):\n    return pile.pop() if pile else None',['Le test protège pop sur une pile vide.','The check protects pop on an empty stack.']),
      task2(['12 · Historique de deux actions','12 · Two-action history'],['Annule les deux dernières actions.','Undo the two latest actions.'],'actions = ["A", "B", "C"]\nfor _ in range(2): print(actions.pop())',['La boucle répète le dépilage.','The loop repeats popping.']),
      task2(['13 · Palindrome','13 · Palindrome'],['Utilise une pile pour comparer un mot à son inverse.','Use a stack to compare a word with its reverse.'],'mot = "kayak"\npile = list(mot)\nprint(mot == "".join(pile.pop() for _ in range(len(pile))))',['La lecture inversée est comparée au mot initial.','Reverse reading is compared with the original word.']),
      task2(['14 · Sommet','14 · Peek'],['Lis le sommet sans dépiler.','Read the top without popping.'],'pile = [10, 20, 30]\nprint(pile[-1])',['L’index -1 observe sans modifier.','Index -1 observes without modifying.']),
      task2(['15 · Vider','15 · Empty'],['Vide une pile en affichant chaque élément.','Empty a stack while displaying each item.'],'pile = [1, 2, 3]\nwhile pile: print(pile.pop())',['while s’arrête quand la pile devient vide.','while stops when the stack becomes empty.'])
    ]
  },
  queues: {
    examples: [
      ex2(['06 · Échantillons','06 · Samples'],['Un laboratoire traite les échantillons dans l’ordre d’arrivée.','A lab processes samples in arrival order.'],'file = ["S1", "S2", "S3"]\nprint(file.pop(0))',['Le plus ancien échantillon est traité en premier.','The oldest sample is processed first.']),
      ex2(['07 · Marathon','07 · Marathon'],['Les coureurs sont appelés au contrôle dans leur ordre.','Runners are called to control in order.'],'file = ["dossard 12", "dossard 18"]\nfile.append("dossard 24")\nprint(file.pop(0))',['append ajoute derrière ; pop(0) sert devant.','append adds behind; pop(0) serves from the front.']),
      ex2(['08 · Capteurs','08 · Sensor messages'],['Une file retient les messages reçus avant analyse.','A queue holds messages received before analysis.'],'messages = ["T=20", "T=21"]\nwhile messages:\n    print("analyse", messages.pop(0))',['La boucle vide la file sans inverser les messages.','The loop empties the queue without reversing messages.']),
      ex2(['09 · Service patient','09 · Patient service'],['Un accueil traite les demandes dans l’ordre d’enregistrement.','A reception processes requests in registration order.'],'demandes = ["A", "B", "C"]\nprochaine = demandes.pop(0)\nprint(prochaine)',['La première demande reste prioritaire dans une file FIFO.','The first request remains first in a FIFO queue.']),
      ex2(['10 · Documents','10 · Documents'],['Une imprimante garde l’ordre des fichiers reçus.','A printer keeps received file order.'],'documents = []\nfor nom in ["a.pdf", "b.pdf"]: documents.append(nom)\nprint(documents.pop(0))',['La file représente l’ordre de service.','The queue represents service order.'])
    ],
    exercises: [
      task2(['11 · Enfiler','11 · Enqueue'],['Ajoute un ticket à une file.','Add a ticket to a queue.'],'file = ["T1"]\nfile.append("T2")',['append place le nouveau ticket derrière.','append places the new ticket behind.']),
      task2(['12 · Servir cinq','12 · Serve five'],['Sers cinq demandes avec while.','Serve five requests with while.'],'file = [1, 2, 3, 4, 5]\nwhile file: print(file.pop(0))',['Chaque retrait respecte FIFO.','Each removal respects FIFO.']),
      task2(['13 · Temps d’attente','13 · Waiting time'],['Additionne les temps de traitement d’une file.','Add processing times in a queue.'],'file = [3, 4, 2]\ntotal = 0\nwhile file: total += file.pop(0)\nprint(total)',['L’accumulateur suit le traitement séquentiel.','The accumulator follows sequential processing.']),
      task2(['14 · Priorité simple','14 · Simple priority'],['Place une urgence en tête d’une file.','Place an emergency at the front.'],'file = ["normal"]\nfile.insert(0, "urgent")\nprint(file.pop(0))',['insert(0) modifie volontairement l’ordre pour la priorité.','insert(0) intentionally changes order for priority.']),
      task2(['15 · Longueur','15 · Length'],['Affiche le nombre de demandes encore en attente.','Display the number of requests waiting.'],'file = ["A", "B", "C"]\nfile.pop(0)\nprint(len(file))',['len mesure l’état courant après un service.','len measures the current state after service.'])
    ]
  },
  trees: {
    examples: [
      ex2(['06 · Classification du vivant','06 · Living classification'],['Une hiérarchie relie règne, classe et espèce.','A hierarchy links kingdom, class, and species.'],'arbre = {"valeur":"Animal", "enfants":[{"valeur":"Mammifère", "enfants":[]}] }\nprint(arbre["valeur"])',['La racine porte le niveau général et les enfants les sous-niveaux.','The root holds the general level and children hold sublevels.']),
      ex2(['07 · Dossiers','07 · Folders'],['Un dossier contient des sous-dossiers et fichiers.','A folder contains subfolders and files.'],'racine = {"nom":"cours", "enfants":[{"nom":"python", "enfants":[]}, {"nom":"data", "enfants":[]}] }\nprint(len(racine["enfants"]))',['La liste enfants porte les branches directes.','The children list holds direct branches.']),
      ex2(['08 · Décision','08 · Decision'],['Un arbre de décision sépare les profils selon un seuil.','A decision tree separates profiles by a threshold.'],'def decision(note):\n    return {"valeur":"reussi" if note >= 10 else "a_reprendre", "enfants":[]}\nprint(decision(14))',['Une branche conditionnelle produit une feuille.','A conditional branch produces a leaf.']),
      ex2(['09 · Compter les feuilles','09 · Count leaves'],['On compte les résultats finaux d’un arbre.','Count final results in a tree.'],'arbre = {"valeur":"Vie", "enfants":[{"valeur":"Animal", "enfants":[]}, {"valeur":"Végétal", "enfants":[]}]}\ndef feuilles(n):\n    if not n["enfants"]: return 1\n    return sum(feuilles(e) for e in n["enfants"])\nprint(feuilles(arbre))',['Le cas d’arrêt est un nœud sans enfant ; les retours totalisent les feuilles.','The stopping case is a node without children; returns total the leaves.']),
      ex2(['10 · Parcours profondeur','10 · Depth traversal'],['Un rapport affiche une hiérarchie avec son niveau.','A report displays a hierarchy with its level.'],'arbre = {"valeur":"Racine", "enfants":[{"valeur":"Gauche", "enfants":[]}, {"valeur":"Droite", "enfants":[]}]}\ndef afficher(n, niveau=0):\n    print("  " * niveau + n["valeur"])\n    for e in n["enfants"]:\n        afficher(e, niveau + 1)\nafficher(arbre)',['Le niveau contrôle l’indentation de la trace et le parcours visite les enfants après la racine.','Level controls indentation and traversal visits children after the root.'])
    ],
    exercises: [
      task2(['11 · Créer un nœud','11 · Create a node'],['Crée un nœud avec valeur et enfants.','Create a node with value and children.'],'noeud = {"valeur": "racine", "enfants": []}',['Le même schéma peut être réutilisé pour chaque nœud.','The same schema can be reused for every node.']),
      task2(['12 · Compter nœuds','12 · Count nodes'],['Compte récursivement tous les nœuds.','Recursively count all nodes.'],'arbre = {"valeur":"A", "enfants":[{"valeur":"B", "enfants":[]}, {"valeur":"C", "enfants":[]}]}\ndef compter(n):\n    return 1 + sum(compter(e) for e in n["enfants"])\nprint(compter(arbre))',['Le nœud courant compte pour 1, puis on ajoute les enfants effectivement visités.','The current node counts as 1, then the visited children are added.']),
      task2(['13 · Chercher valeur','13 · Search value'],['Cherche une valeur dans un arbre.','Search for a value in a tree.'],'arbre = {"valeur":"Racine", "enfants":[{"valeur":"Python", "enfants":[]}, {"valeur":"Data", "enfants":[]}]}\ndef contient(n, cible):\n    return n["valeur"] == cible or any(contient(e, cible) for e in n["enfants"])\nprint(contient(arbre, "Data"))',['or et any arrêtent la recherche dès qu’une branche réussit.','or and any stop once a branch succeeds.']),
      task2(['14 · Hauteur','14 · Height'],['Calcule la hauteur d’un arbre.','Calculate tree height.'],'arbre = {"valeur":"A", "enfants":[{"valeur":"B", "enfants":[{"valeur":"C", "enfants":[]}]}]}\ndef hauteur(n):\n    if not n["enfants"]: return 0\n    return 1 + max(hauteur(e) for e in n["enfants"])\nprint(hauteur(arbre))',['La hauteur d’une feuille est zéro ; les retours remontent ensuite la profondeur.','A leaf has height zero; returns then build the depth.']),
      task2(['15 · Afficher feuilles','15 · Display leaves'],['Affiche uniquement les feuilles.','Display leaves only.'],'arbre = {"valeur":"A", "enfants":[{"valeur":"B", "enfants":[]}, {"valeur":"C", "enfants":[]}]}\ndef afficher_feuilles(n):\n    if not n["enfants"]:\n        print(n["valeur"])\n    for e in n["enfants"]:\n        afficher_feuilles(e)\nafficher_feuilles(arbre)',['La récursion descend jusqu’aux nœuds sans enfants et affiche chacune des feuilles.','Recursion descends to nodes without children and displays each leaf.'])
    ]
  },
  statistics: {
    examples: [
      ex2(['06 · Fréquence cardiaque','06 · Heart rate'],['Une série de fréquences est résumée par moyenne et étendue.','A heart-rate series is summarized by mean and range.'],'fc = [62, 70, 78, 66]\nprint(sum(fc)/len(fc), max(fc)-min(fc))',['Deux indicateurs décrivent niveau et dispersion simple.','Two indicators describe level and simple spread.']),
      ex2(['07 · Population bactérienne','07 · Bacterial population'],['Une suite de mesures suit une croissance par jour.','A series follows growth by day.'],'pop = [100, 120, 150, 190]\nvariations = [pop[i+1]-pop[i] for i in range(len(pop)-1)]\nprint(variations)',['Les différences successives décrivent la dynamique.','Successive differences describe the dynamics.']),
      ex2(['08 · Quartiles simples','08 · Simple quartiles'],['Des mesures triées sont séparées en deux moitiés.','Sorted measures are split into two halves.'],'valeurs = sorted([2, 4, 5, 8, 10, 12])\nprint(valeurs[:3], valeurs[3:])',['Le découpage permet une première lecture de dispersion.','Splitting gives a first reading of spread.']),
      ex2(['09 · Fréquences','09 · Frequencies'],['On compte les occurrences de notes dans une classe.','Count grade occurrences in a class.'],'notes = [10, 12, 10, 15, 12, 10]\nprint({n: notes.count(n) for n in set(notes)})',['La fréquence absolue de chaque valeur est observable.','The absolute frequency of each value is observable.']),
      ex2(['10 · Interprétation','10 · Interpretation'],['Une moyenne est comparée à un objectif pédagogique.','A mean is compared to a learning target.'],'moyenne = 13.4\nobjectif = 12\nprint("objectif atteint" if moyenne >= objectif else "notion à retravailler")',['Le calcul devient une décision interprétée.','The calculation becomes an interpreted decision.'])
    ],
    exercises: [
      task2(['11 · Moyenne pondérée','11 · Weighted mean'],['Calcule une moyenne avec coefficients.','Calculate a weighted mean.'],'notes = [12, 16]\ncoeffs = [1, 2]\nprint(sum(n*c for n,c in zip(notes, coeffs)) / sum(coeffs))',['zip associe chaque note à son coefficient.','zip pairs each grade with its coefficient.']),
      task2(['12 · Taux d’évolution','12 · Growth rate'],['Calcule l’évolution de 100 à 125.','Calculate growth from 100 to 125.'],'ancien, nouveau = 100, 125\nprint((nouveau - ancien) / ancien * 100)',['Le taux compare variation et valeur de départ.','The rate compares change with starting value.']),
      task2(['13 · Médiane impaire','13 · Odd median'],['Trouve la médiane de cinq mesures.','Find the median of five measurements.'],'valeurs = sorted([9, 2, 7, 4, 5])\nprint(valeurs[len(valeurs)//2])',['Le tri rend l’indice central significatif.','Sorting makes the central index meaningful.']),
      task2(['14 · Données manquantes','14 · Missing data'],['Ignore les valeurs None avant moyenne.','Ignore None values before averaging.'],'valeurs = [10, None, 14]\npropres = [v for v in valeurs if v is not None]\nprint(sum(propres)/len(propres))',['La préparation des données précède le calcul.','Data preparation precedes calculation.']),
      task2(['15 · Comparaison de groupes','15 · Compare groups'],['Compare la moyenne de deux groupes de notes.','Compare the mean of two grade groups.'],'a, b = [12, 14], [15, 16]\nma, mb = sum(a)/len(a), sum(b)/len(b)\nprint("B" if mb > ma else "A")',['Les deux moyennes sont calculées avant la comparaison.','Both means are calculated before comparison.'])
    ]
  }
};
window.EXTRA_CHAPTERS = E;
