(function(){
  const pair=(fr,en)=>({fr,en});
  const q=(fr,en,choices,answer)=>({prompt:pair(fr,en),choices:choices.map(([a,b])=>pair(a,b)),answer});
  const complexities={constant:pair('Temps O(1) · espace O(1)','Time O(1) · space O(1)'),linear:pair('Temps O(n) · espace O(1)','Time O(n) · space O(1)'),quadratic:pair('Temps O(n²) · espace O(1)','Time O(n²) · space O(1)')};
  const conditionExamples=[
    ['Température', 'Temperature','t = 18\nif t < 0:\n    etat = "solide"\nelif t < 100:\n    etat = "liquide"\nelse:\n    etat = "gaz"\nprint(etat)', 'Trois intervalles sont testés du plus restrictif au plus large.','Three intervals are tested from narrowest to widest.',complexities.constant],
    ['Âge et autorisation','Age and permission','age = 16\nparent = True\nif age >= 18:\n    autorise = True\nelif age >= 14 and parent:\n    autorise = True\nelse:\n    autorise = False\nprint(autorise)','La condition imbriquée combine âge et accord parental.','The nested condition combines age and parental consent.',complexities.constant],
    ['Note et mention','Grade and distinction','note = 15\nif note >= 10:\n    if note >= 16:\n        mention = "très bien"\n    else:\n        mention = "réussite"\nelse:\n    mention = "à revoir"\nprint(mention)','Le second if n’est évalué que si le premier est vrai.','The second if is evaluated only when the first is true.',complexities.constant],
    ['Feu tricolore','Traffic light','couleur = "orange"\nurgence = False\nif couleur == "rouge":\n    action = "arrêt"\nelif couleur == "orange":\n    if urgence:\n        action = "prudence renforcée"\n    else:\n        action = "ralentir"\nelse:\n    action = "avancer"\nprint(action)','Une condition interne précise le cas orange.','An inner condition refines the orange case.',complexities.constant],
    ['Triangle valide','Valid triangle','a, b, c = 3, 4, 5\nif a + b > c and a + c > b and b + c > a:\n    if a*a + b*b == c*c:\n        nature = "rectangle"\n    else:\n        nature = "valide"\nelse:\n    nature = "impossible"\nprint(nature)','On vérifie d’abord la validité, puis la nature.','Validity is checked first, then the type.',complexities.constant],
    ['Batterie','Battery','niveau = 22\nchargeur = True\nif niveau < 20:\n    if chargeur:\n        message = "charger"\n    else:\n        message = "chercher une prise"\nelse:\n    message = "continuer"\nprint(message)','La branche interne dépend du niveau critique.','The inner branch depends on the critical level.',complexities.constant],
    ['Vitesse et route','Speed and road','vitesse = 72\nroute = "ville"\nif route == "ville":\n    if vitesse > 50:\n        message = "ralentir"\n    else:\n        message = "correct"\nelse:\n    message = "route à analyser"\nprint(message)','La route choisit d’abord le contexte de comparaison.','The road first selects the comparison context.',complexities.constant],
    ['Accès sécurisé','Secure access','code = "A7"\nactif = True\nif actif:\n    if len(code) >= 2:\n        acces = "autorisé"\n    else:\n        acces = "code trop court"\nelse:\n    acces = "compte inactif"\nprint(acces)','Chaque niveau réduit l’ensemble des cas possibles.','Each level reduces the set of possible cases.',complexities.constant],
    ['Stock et commande','Stock and order','stock = 8\ncommande = 5\nif commande > 0:\n    if commande <= stock:\n        resultat = "préparer"\n    else:\n        resultat = "stock insuffisant"\nelse:\n    resultat = "commande invalide"\nprint(resultat)','La commande est validée avant la comparaison au stock.','The order is validated before comparing it to stock.',complexities.constant],
    ['Moyenne et présence','Average and attendance','moyenne = 13\npresents = 4\nif presents > 0:\n    if moyenne >= 10:\n        decision = "validé"\n    else:\n        decision = "remédiation"\nelse:\n    decision = "aucune décision"\nprint(decision)','L’absence de présents est traitée avant la moyenne.','No attendees are handled before the average.',complexities.constant]
  ];
  const multipleExamples=[
    ['Météo','Weather','pluie = False\nvent = 12\ntemperature = 9\nif pluie:\n    conseil = "imperméable"\nelif vent > 30:\n    conseil = "vêtement coupe-vent"\nelif temperature < 10:\n    conseil = "veste chaude"\nelse:\n    conseil = "tenue légère"\nprint(conseil)','elif sélectionne le premier cas vrai.','elif selects the first true case.',complexities.constant],
    ['Tarif transport','Transport fare','age = 17\nif age < 6:\n    tarif = 0\nelif age < 18:\n    tarif = 2\nelif age < 65:\n    tarif = 3\nelse:\n    tarif = 1','Les seuils sont ordonnés sans chevauchement utile.','Thresholds are ordered without useful overlap.',complexities.constant],
    ['Score sportif','Sports score','score = 74\nif score >= 90:\n    niveau = "élite"\nelif score >= 75:\n    niveau = "avancé"\nelif score >= 50:\n    niveau = "intermédiaire"\nelse:\n    niveau = "débutant"\nprint(niveau)','La comparaison descendante évite un classement prématuré.','Descending comparisons avoid premature classification.',complexities.constant],
    ['Qualité de l’air','Air quality','indice = 82\nif indice <= 25: niveau = "bon"\nelif indice <= 50: niveau = "modéré"\nelif indice <= 100: niveau = "dégradé"\nelse: niveau = "critique"\nprint(niveau)','Chaque intervalle possède une borne explicite.','Each interval has an explicit bound.',complexities.constant],
    ['Calculatrice','Calculator','a, b, op = 12, 4, "/"\nif op == "+": resultat = a + b\nelif op == "-": resultat = a - b\nelif op == "*": resultat = a * b\nelif op == "/" and b != 0: resultat = a / b\nelse: resultat = "erreur"\nprint(resultat)','La dernière branche protège les opérateurs inconnus et la division par zéro.','The final branch protects unknown operators and division by zero.',complexities.constant],
    ['Taille de fichier','File size','ko = 840\nif ko < 100:\n    classe = "petit"\nelif ko < 1000:\n    classe = "moyen"\nelse:\n    classe = "grand"\nprint(classe)','Une seule branche est exécutée.','Only one branch is executed.',complexities.constant],
    ['Température ressentie','Feels-like temperature','ressentie = 4\nif ressentie < 0: risque = "gel"\nelif ressentie < 8: risque = "froid"\nelif ressentie < 18: risque = "frais"\nelse: risque = "doux"\nprint(risque)','Le classement transforme une mesure en décision.','The classification turns a measurement into a decision.',complexities.constant],
    ['Énergie restante','Remaining energy','energie = 38\nif energie <= 10: etat = "critique"\nelif energie <= 30: etat = "faible"\nelif energie <= 60: etat = "correcte"\nelse: etat = "haute"\nprint(etat)','Les bornes inclusives sont lisibles dans le code.','Inclusive bounds are readable in code.',complexities.constant],
    ['Priorité ticket','Ticket priority','attente = 48\nif attente > 120: priorite = "urgente"\nelif attente > 60: priorite = "haute"\nelif attente > 20: priorite = "normale"\nelse: priorite = "basse"\nprint(priorite)','La valeur est convertie en niveau de service.','The value is converted into a service level.',complexities.constant],
    ['Indice de masse','Mass index','imc = 24.2\nif imc < 18.5: categorie = "bas"\nelif imc < 25: categorie = "référence"\nelif imc < 30: categorie = "haut"\nelse: categorie = "très haut"\nprint(categorie)','La classification est informative et ne remplace pas un avis médical.','The classification is informative and does not replace medical advice.',complexities.constant]
  ];
  const forExamples=[
    ['Compter de 0 à 4','Count from 0 to 4','for i in range(5):\n    print(i)','range(5) produit 0, 1, 2, 3, 4.','range(5) produces 0, 1, 2, 3, 4.',complexities.linear],
    ['Somme des entiers','Sum integers','total = 0\nfor i in range(1, 6):\n    total += i\nprint(total)','L’accumulateur vaut 1, 3, 6, 10 puis 15.','The accumulator becomes 1, 3, 6, 10, then 15.',complexities.linear],
    ['Carrés','Squares','for i in range(1, 5):\n    print(i * i)','Chaque tour calcule un carré indépendant.','Each turn computes an independent square.',complexities.linear],
    ['Pairs','Even numbers','for i in range(0, 11, 2):\n    print(i)','Le pas 2 saute directement au pair suivant.','Step 2 jumps directly to the next even number.',complexities.linear],
    ['Table de multiplication','Multiplication table','n = 7\nfor i in range(1, 6):\n    print(n * i)','La variable i prend cinq valeurs.','Variable i takes five values.',complexities.linear],
    ['Compter les voyelles','Count vowels','mot = "python"\ncompte = 0\nfor i in range(len(mot)):\n    if mot[i] in "aeiouy":\n        compte += 1\nprint(compte)','range parcourt les indices du mot et compte les voyelles.','range traverses word indices and counts vowels.',complexities.linear],
    ['Maximum borné','Bounded maximum','valeurs = [4, 9, 2, 7]\nmaximum = valeurs[0]\nfor i in range(1, len(valeurs)):\n    if valeurs[i] > maximum:\n        maximum = valeurs[i]\nprint(maximum)','La comparaison visite chaque position une fois.','The comparison visits each position once.',complexities.linear],
    ['Grille simple','Simple grid','for ligne in range(2):\n    for colonne in range(3):\n        print(ligne, colonne)','Deux boucles donnent 2 × 3 = 6 couples.','Two loops give 2 × 3 = 6 pairs.',complexities.quadratic],
    ['Moyenne','Average','notes = [12, 15, 9]\ntotal = 0\nfor i in range(len(notes)):\n    total += notes[i]\nprint(total / len(notes))','Le total 36 est divisé par 3 : 12.','Total 36 is divided by 3: 12.',complexities.linear],
    ['Compte à rebours','Countdown','for i in range(5, 0, -1):\n    print(i)','Le pas négatif diminue la valeur jusqu’à 1.','Negative step decreases the value to 1.',complexities.linear]
  ];
  const whileExamples=[
    ['Compter jusqu’à 4','Count to 4','i = 0\nwhile i < 5:\n    print(i)\n    i += 1','La condition est revérifiée après chaque modification.','The condition is checked again after each update.',complexities.linear],
    ['Somme jusqu’à un seuil','Sum to a threshold','total = 0\ni = 1\nwhile total < 10:\n    total += i\n    i += 1\nprint(total)','L’invariant est total < 10 au début de chaque tour.','The invariant is total < 10 at the start of each turn.',complexities.linear],
    ['Saisie contrôlée','Validated input','age = 0\nwhile age < 1 or age > 120:\n    age = 18\nprint(age)','La boucle protège un intervalle de valeurs.','The loop protects a valid interval.',complexities.linear],
    ['Décompte','Countdown','n = 5\nwhile n > 0:\n    print(n)\n    n -= 1','La mesure qui rapproche de l’arrêt est n.','The measure approaching termination is n.',complexities.linear],
    ['Recherche séquentielle','Sequential search','valeurs = [3, 8, 5, 9]\ni = 0\nwhile i < len(valeurs) and valeurs[i] != 5:\n    i += 1\nprint(i)','La recherche s’arrête sur la première occurrence.','Search stops at the first occurrence.',complexities.linear],
    ['Puissance de deux','Power of two','valeur = 1\nwhile valeur < 100:\n    valeur *= 2\nprint(valeur)','La valeur double : 1, 2, 4, 8, 16, 32, 64, 128.','The value doubles: 1, 2, 4, 8, 16, 32, 64, 128.',complexities.linear],
    ['Menu','Menu','choix = "q"\nwhile choix != "q":\n    choix = "q"\nprint("fin")','La sentinelle q indique la fin.','Sentinel q indicates the end.',complexities.linear],
    ['Euclide','Euclid','a, b = 48, 18\nwhile b != 0:\n    a, b = b, a % b\nprint(a)','Le reste diminue jusqu’à zéro ; le PGCD vaut 6.','The remainder decreases to zero; GCD is 6.',complexities.linear],
    ['Accumuler des notes','Accumulate grades','notes = [10, 14, 16]\ni = 0\ntotal = 0\nwhile i < len(notes):\n    total += notes[i]\n    i += 1\nprint(total)','i avance d’une position par tour.','i advances one position per turn.',complexities.linear],
    ['Fenêtre de temps','Time window','minute = 0\nwhile minute <= 30:\n    minute += 10\nprint(minute)','La boucle effectue quatre contrôles : 0, 10, 20, 30.','The loop checks four values: 0, 10, 20, 30.',complexities.linear]
  ];
  function pack(id,title,subtitle,body,examples,exerciseCodes){
    const mapped=examples.map((x,i)=>({title:pair(`${String(i+1).padStart(2,'0')} · ${x[0]}`,`${String(i+1).padStart(2,'0')} · ${x[1]}`),context:pair(`Situation : ${x[0]}. ${x[3]}`,`Situation: ${x[1]}. ${x[4]}`),code:x[2],explanation:pair(x[3],x[4]),complexity:x[5]}));
    const exercises=Array.from({length:15},(_,i)=>{const x=exerciseCodes[i%exerciseCodes.length];return {title:pair(`${String(i+1).padStart(2,'0')} · Exercice ${x[0]}`,`${String(i+1).padStart(2,'0')} · Exercise ${x[1]}`),prompt:pair(x[2],x[3]),solution:x[4],correction:pair(`${x[5]} Complexité : ${x[6].fr}.`,` ${x[5]} Complexity: ${x[6].en}.`),complexity:x[6]};});
    return {id,title:pair(title[0],title[1]),subtitle:pair(subtitle[0],subtitle[1]),body:pair(body[0],body[1]),vocab:[{word:pair('Condition','Condition'),definition:pair('Expression vraie ou fausse.','True or false expression.')},{word:pair('Trace','Trace'),definition:pair('Suite des valeurs observées.','Sequence of observed values.')},{word:pair('Complexité','Complexity'),definition:pair('Coût en temps et mémoire.','Time and memory cost.')}],example:mapped[0].code,trace:[pair('Lire les valeurs initiales.','Read initial values.'),pair('Exécuter la condition ou le tour courant.','Execute the current condition or iteration.'),pair('Mettre à jour les variables.','Update variables.'),pair('Vérifier la condition suivante.','Check the next condition.')],situation:pair('Situation de départ : observer une décision ou une répétition.','Starting situation: observe a decision or repetition.'),solution:mapped[0].code,explanation:pair('Une trace complète relie instruction, valeurs intermédiaires, état mémoire et complexité.','A complete trace links instruction, intermediate values, memory state, and complexity.'),questions:[q('Quel élément faut-il tracer ?','What should be traced?',[['La valeur et la condition','Value and condition'],['Seulement le résultat','Only result'],['Aucun état','No state']],0),q('Que signifie O(n) ?','What does O(n) mean?',[['Coût proportionnel à n','Cost proportional to n'],['Coût nul','Zero cost'],['Une erreur','An error']],0),q('Pourquoi modifier un compteur ?','Why update a counter?',[['Garantir la progression','Guarantee progress'],['Créer une erreur','Create error'],['Supprimer la condition','Delete condition']],0),q('Que montre une adresse symbolique ?','What does a symbolic address show?',[['Une localisation conceptuelle','A conceptual location'],['Une adresse physique réelle','A real physical address'],['Un type de boucle','A loop type']],0),q('Quand vérifier la complexité ?','When should complexity be checked?',[['Après avoir identifié les tours','After identifying iterations'],['Jamais','Never'],['Avant d’écrire le titre','Before title']],0)],examples:mapped,exercises};
  }
  const exCodes=[['Condition','Condition','Écris une condition qui distingue pair et impair.','Write a condition distinguishing even and odd.','n = 14\nif n % 2 == 0: resultat = "pair"\nelse: resultat = "impair"\nprint(resultat)','La condition teste le reste de la division.',complexities.constant],['Seuil','Threshold','Classe une valeur selon trois seuils.','Class a value using three thresholds.','x = 42\nif x < 10: classe = "A"\nelif x < 50: classe = "B"\nelse: classe = "C"\nprint(classe)','Les branches sont testées dans l’ordre.',complexities.constant],['Validation','Validation','Refuse une valeur hors intervalle.','Reject an out-of-range value.','x = 12\nif 0 <= x <= 20: print("ok")\nelse: print("erreur")','La comparaison chaînée vérifie deux bornes.',complexities.constant]];
  const forCodes=[['Somme','Sum','Calcule la somme des nombres de 1 à 10 avec for in range.','Calculate the sum from 1 to 10 with for in range.','total = 0\nfor i in range(1, 11): total += i\nprint(total)','L’accumulateur est mis à jour dix fois.',complexities.linear],['Pairs','Evens','Affiche les pairs avec for in range et un pas.','Display evens with for in range and a step.','for i in range(0, 21, 2): print(i)','Le pas 2 réduit les tours à 11.',complexities.linear],['Grille','Grid','Compte les couples d’une grille 3 × 4.','Count pairs in a 3 × 4 grid.','compte = 0\nfor i in range(3):\n    for j in range(4): compte += 1\nprint(compte)','Deux boucles imbriquées donnent 12 tours.',complexities.quadratic]];
  const whileCodes=[['Compteur','Counter','Écris un while avec compteur et arrêt explicite.','Write a while with a counter and explicit stop.','i = 0\nwhile i < 6:\n    print(i)\n    i += 1','Le compteur avance à chaque tour.',complexities.linear],['Sentinelle','Sentinel','Répète jusqu’à rencontrer une sentinelle.','Repeat until reaching a sentinel.','n = 3\nwhile n != 0:\n    n -= 1\nprint("fin")','La sentinelle 0 termine le parcours.',complexities.linear],['Recherche','Search','Recherche une valeur avec while et un indice.','Search for a value with while and an index.','a = [2, 5, 8]\ni = 0\nwhile i < len(a) and a[i] != 5: i += 1\nprint(i)','Chaque indice est examiné au plus une fois.',complexities.linear]];
  window.GENERALIZED_CHAPTERS=[pack('conditions_nested',['Conditions imbriquées','Nested conditions'],['Décider par niveaux et tracer chaque branche.','Decide by levels and trace each branch.'],['Une condition imbriquée ouvre un second choix seulement dans une branche déjà sélectionnée. La trace doit noter chaque test et la valeur produite.','A nested condition opens a second choice only inside an already selected branch. The trace must record each test and produced value.'],conditionExamples,exCodes),pack('conditions_multiple',['Conditions multiples','Multiple conditions'],['Organiser if, elif et else sans confondre les seuils.','Organize if, elif, and else without confusing thresholds.'],['Les conditions multiples parcourent une chaîne de choix. Une seule branche est exécutée, la première qui est vraie.','Multiple conditions scan a chain of choices. One branch runs: the first true one.'],multipleExamples,exCodes),pack('for_range',['Boucle for in range','for in range loop'],['Répéter un nombre de fois connu et calculer la complexité.','Repeat a known number of times and calculate complexity.'],['for in range produit une suite d’indices ou de valeurs. La trace montre l’itération, l’accumulateur et le nombre de tours.','for in range produces a sequence of indices or values. The trace shows iteration, accumulator, and number of turns.'],forExamples,forCodes),pack('while_loop',['Boucle while','while loop'],['Répéter tant qu’une condition reste vraie sans oublier l’arrêt.','Repeat while a condition remains true without forgetting termination.'],['while dépend d’une condition réévaluée. Une variable de contrôle doit progresser pour éviter la boucle infinie.','while depends on a reevaluated condition. A control variable must progress to avoid an infinite loop.'],whileExamples,whileCodes)];
})();
